logging:
 path: logs
 file: mylog.log

spring:
  application:
        name: myTest
  datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://172.16.210.70:3306/test
       username: root
       password: root123

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*
