logging: 
 path: logs
 file: mylog.log

Spring: 
  application:
    name: myTest
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root123


mybatis: 
  type-aliases-package: com.example.demo
  mapper-locations: 
    - mapper/*
     

